### ISSUE TITLE
Support for Office 365 for Business

### ISSUE THREAD

**Issue by kedarbhise** [ennswi/AndroidCaldavSyncAdapater#11]
Hi,

My work uses an Office 365 for Business account. I use standard IMAP client to sync email.
I use CaldavSyncAdapter (from @gggard) to sync multiple calendars onto my Android Device.

Does this tool support Office 365 Calendar Sync?
If yes, what are the settings to be used?

**Comment by ennswi** [comment]
Hi,
I don't know, i doesn't use office 365. 

It would be great if you try it and reply the answer.
