### ISSUE TITLE
duplicated dates in calendar

### ISSUE THREAD

**Issue by didderot** [ennswi/AndroidCaldavSyncAdapater#12]
Hi,

I'm not sure if this is an issue of aCalDav or the Calendar, but maybe you can reproduce this:
I'm using CyanogenMod M12 with Calendar 4.4.4 and try to sync it with my owncloud 7 using SSL. In general the sync works - when I add a date into the calendar of the phone and click 'refresh', the date appears in owncloud. But when I refresh again (in the phone) a second date appears in the calendar of the phone. It looks like the sync reimported the date back from owncloud, not realizing that it is the same date. On the owncloud-side the date stays 'singleton' - just on the phone, I have a second one.
This makes the sync unusable for me, since I want to use it primary from phone to server and not the other way. 

thanks for any reply
diddi

**Comment by schulmar** [comment]
I can confirm this behavior on CyanogenMod 11 and owncloud 8.

It also happens with the CalDav Sync Adapter from which this repository was forked.

**Comment by protist** [comment]
I just wanted to mention that I don't see this bug with CyanogenMod 11, OwnCloud 8.2 and Business Calendar 2. If I press "Sync" on Android's Business Calendar 2, the event is not duplicated.
