### ISSUE TITLE
Pre-compiled builds

### ISSUE THREAD

**Issue by djmattyg007** [ennswi/AndroidCaldavSyncAdapater#14]
I don't have the ability to compile this myself, and was wondering if you provided pre-compiled builds for download anywhere, as I'd very much like to try it out.

**Comment by ennswi** [comment]
You can download the App on f-droid.

https://f-droid.org/app/de.we.acaldav

**Comment by djmattyg007** [comment]
You should put a link to the F-Droid page in the readme file.
