### ISSUE TITLE
Battery drain when CalDAV server is offline

### ISSUE THREAD

**Issue by eloo** [ennswi/AndroidCaldavSyncAdapater#17]
Hey guys,
i noticed a battery drain tonight when my CalDAV server was offline.
It seems that ACalDAV is trying to sync in regular time when the server is offline. This seems to be a huge problem even when your abroad. 
What about if we raise the polling frequency once the server is offline and try only to ping the server first if the server was gone at the last sync attempt?
To improve the "reconnect" to the CalDAV server when you're abroad or so, we can try to ping the server when the device is connected to a WiFi network.
what do you all mean?

Regards, 
Eloo

**Comment by kallegit1950** [comment]
Hi,
so you have a certain refresh intervall, let's say 30 minutes. If the server is online every 30 minutes you do a request to a server which succeeds. If the server is offline you do a request every 30 minutes and that fails. Do you have an idea why a failed try is usinig more battery than a suceeded try? I only started to look into CalDAV, so maybe I think too simplistic about it. But for me that doesn't sound logical at the moment.

Regards, K.

**Comment by qknight** [comment]
i see https://lastlog.de/blog/posts/media/aCalDAV-issue17.png this a lot if owncloud is down. 

# implementation idea
- only create one notification, if that is clicked 
  - show a log of failed sync-attempts and 
  - list the time of the last successful sync
- currently connection settings can only be changed for `new CalDAV endpoints` or when there is an connection issue. i would rather like to have a configuration dialog as there is for `CardDAV-Sync free`

how much effort would both features be? anyone wants to implement that? i can provide a little funding for that. 

# blog posting

despite this bug, everything works nicely with my setup! thanks for creating this software.

this is documented here:
https://lastlog.de/blog/posts/android_calendar_and_CalDav.html

**Comment by ennswi** [comment]
@qknight

The most of us doesn't need some funds.
What we need is more time.
We do this in our free time.

If you found some who implement the features, that would be great and I'll do a new release.
