### ISSUE TITLE
Code Question AuthenticatorActivity.java

### ISSUE THREAD

**Issue by kallegit1950** [ennswi/AndroidCaldavSyncAdapater#19]
In the AsyncTask of the above activity in switch(result), case(SUCCESS) there is this code

``` java
case SUCCESS:
                    boolean OldAccount = false;
                    LoginResult Result = LoginResult.Success_Calendar;

                    if (OldAccount) {//more code here
```

In the development branch on line 460. What is this OldAccount good for? I cannot see what this variable is good for and where it is being used or where the if ever can evaluate to true. Is that some kind of "we leave some old code, just in case"? If so does it make sense for some reason to keep it or can this be removed for better readability? From my point of view uncommenting code and leaving a comment would be the better option in such case.

**Comment by Enrico204** [comment]
+1

I'll do a pull request for that
