### ISSUE TITLE
Shibboleth/OpenID Connect/Oauth2

### ISSUE THREAD

**Issue by treveradams** [ennswi/AndroidCaldavSyncAdapater#22]
More of a question:

Does aCalDavSync support a BedeWork server protected by any of those systems (Shibboleth is SAML, so SAML with Ipsilon would also be part of this question)?

If not, would it be possible? I would prefer Shibboleth as it has IdP, Service Provider, and full federation.

**Comment by ennswi** [comment]
The APP does not support shibbeloth. 
If BedeWork use caldav, then it should be work.
