### ISSUE TITLE
aCalDav stop syncing

### ISSUE THREAD

**Issue by dev-http** [ennswi/AndroidCaldavSyncAdapater#24]
Hello,
When I install aCalDav, I setup sync every 15minutes.
At the beginning, the sync is perfect, but, after one or two days, the sync stop...
So, I uncheck and re-check the sync option, and it works only for one time...
I'm under Android 4.4.4
Thanks for your support.

Lionel

**Comment by carlmartus** [comment]
I have this problem also. Syncing every 120 minutes. Worked when I set it up. Now it doesn't autosync and manual sync doesn't work.

**Comment by AlexandreBonneau** [comment]
I'm hitting the problem for a month now.
Before 15/02/2017 everything was working great, but since then the synchronization is not done anymore, even when you try to force it.

I'm trying to synchronize with owncloud (I triple checked the credentials).

aCalDav v0.1.1
Android 7.0

**Comment by AlexandreBonneau** [comment]
The problem is unfortunately still present today.

Could please re-open that issue?
