### ISSUE TITLE
Problem SelfSigned SSL

### ISSUE THREAD

**Issue by aikie** [ennswi/AndroidCaldavSyncAdapater#29]
In v0.0.5 SelfSigned SSL did work fine, but starting from v0.0.6 I do get an SSL error when I try to add a new account. I did uncheck the "Check SSL Certificate". I tried checking the "Check SSL Certificate" but that didn't solve the problem either. I downgraded back to v0.0.5 now I can add my accounts again.

Android 5.0.1 on Samsung GT-i9505

**Comment by ennswi** [comment]
@aikie,
can you test the changes feom development branch.

If you can't,
can you create an test account where  i can check this?

**Comment by jonnius** [comment]
Send me an e-mail and I create a test account for you. jonatan_zeidler@gmx.de

**Comment by ennswi** [comment]
Thanks @jonnius you can delete the test account, now it's fixed.

**Comment by jonnius** [comment]
:+1:
