### ISSUE TITLE
Package id mismatch

### ISSUE THREAD

**Issue by ghost** [ennswi/AndroidCaldavSyncAdapater#3]
AndroidManifest.xml uses `de.jdevel.acaldav` while gradle uses `de.we.acaldav`, which is the correct one?

**Comment by ennswi** [comment]
de.we.acaldav is the right.

**Comment by ennswi** [comment]
no it should work

**Comment by ennswi** [comment]
if you want to build them, use the develop branch.
I use the git flow.

if you want i can make a release.

**Comment by ennswi** [comment]
ok, i update the release. 
no the release should work

**Comment by ghost** [comment]
You might want to change the package name in ACalDAV/AndroidManifest.xml as well. While gradle should override it, this only happens on build-time. So any operations applied before have to deal with two package ids. 

E.g. we at FDroid, a free/libre/open-source app "market" have scripts that watch app repositories for commits changeing version name and versioncode. Currently they get confused, since they cannot decide which package id to use :). While this is a issue with our updatechecks, it would be nice to solve this upstream as well.

**Comment by ennswi** [comment]
Hi,

now it's solved.

Thanks for the Information.

**Comment by ghost** [comment]
Yep, updatechecks seem to work. Thanks for the quick response!
