### ISSUE TITLE
Why the fork ?

### ISSUE THREAD

**Issue by strk** [ennswi/AndroidCaldavSyncAdapater#39]
Why was this fork made ? What's the future plan ?

**Comment by ennswi** [comment]
Hi

To continue the development.
Add feathers and fixing bugs.

A plan is a bit difficult.
I do this in my free time, same as the others. 
If there is no free time, we cannot work.

If you want work with us together, feel free.

**Comment by strk** [comment]
I'm happy to help, just want to be sure it's the right place. Was the original author contacted ? Any background info about who's helping with this fork ? Why was a name change not needed ?

**Comment by strk** [comment]
Also I'm confused by README pointing to original wiki (https://github.com/gggard/AndroidCaldavSyncAdapater/wiki) which talks about gggard versions 1.8 whils latest release of this one is 0.1 ...

**Comment by strk** [comment]
I Found DavDroid also does the syncing, and seems to be working better.
FYI: [DavDroid](https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=at.bitfire.davdroid)

**Comment by strk** [comment]
For the record: DavDroid is also having problems, *and* does not have a proper issue tracker, so I'm considering switching back. It's unfortunate I didn't specify more about `working better` because it could have been a false impression.
