### ISSUE TITLE
Test result latest build on F-Droid

### ISSUE THREAD

**Issue by ervee** [ennswi/AndroidCaldavSyncAdapater#4]
Hi,

I tested your recent release on Android 4.3 and 4.4.2 x86 VM's. More to come.

Here is what I found so far:
- If CalDAV Sync Adapter is installed, your App does not show when configuring a new sync account. It does show CalDavSync Adapter.
- When setting up the account, it asks for an update interval. I think there should be some sort of default when you enter nothing. Or let the system decide. How does this interval work? According to gggard this should not be possible in sync adapters. https://github.com/gggard/AndroidCaldavSyncAdapater/issues/231  
- There is no Change password option :( There really should be.

Ralf.

**Comment by ennswi** [comment]
Hi,

can you please make an issue from each point.
