### ISSUE TITLE
What are the differences with davdroid?

### ISSUE THREAD

**Issue by DamienCassou** [ennswi/AndroidCaldavSyncAdapater#42]
In case you don't know: https://davdroid.bitfire.at/

**Comment by 1u** [comment]
@DamienCassou thx for the hint.
I think DAVdroid is much better maintained (see [Forum](https://forums.bitfire.at/category/4/davdroid) and [Source](https://gitlab.com/bitfireAT/davdroid/graphs/master)) and has a handier interface and settings (ex. auto-search for calendars, sync colors, etc.)
cheers!

**Comment by DamienCassou** [comment]
Any reason to use AndroidCaldavSyncAdapater?

**Comment by 1u** [comment]
I didn't find one. After I saw your link above I stopped. :) 
Main reason: I constantly got strange error messages from aCalDav ("removed calendar", "fond calendar"..) and additionally aCalDav used 370 MB mobiledata in one week for 3 calendars with a total of max. 50 events each)
