### ISSUE TITLE
App does not show when CalDAV Sync Adapter is installed

### ISSUE THREAD

**Issue by ervee** [ennswi/AndroidCaldavSyncAdapater#5]
Hi,

Subject says it all. If CalDAV Sync Adapter is installed, your App does not show when configuring a new sync account. It does show CalDavSync Adapter.

Ralf.

**Comment by de4niih** [comment]
@ervee Please have in mind that the App doenst have a Launcher Icon. Just head over to Settings => Accounts => Add account in Android and there you will see the CalDAV Sync Adapter App Icon.
For managin your Sync Settings just open your account and there you can change your settings.

**Comment by ervee** [comment]
I know. But when the CalDAV Sync Adapter (from play store) is installed, @ennswi's from F-Droid does not show up when configuring an account.

**Comment by de4niih** [comment]
@ervee @ennswi 
![screenshot_2015-03-03-13-27-16](https://cloud.githubusercontent.com/assets/11258944/6462657/28670d24-c1ab-11e4-868d-c463461140e0.png)
Nope. Works good for me.
Running latest Android 5.0.2

**Comment by ennswi** [comment]
if an Account is valid, then you get a short Toast Notification, and a Notification with the name of the Calendar in the notigicationbar.
