### ISSUE TITLE
No change password option

### ISSUE THREAD

**Issue by ervee** [ennswi/AndroidCaldavSyncAdapater#7]
Hi,

There is no Change password option :( There really should be. I've had users losing a lot of calendar updates because they changed the password at the server side and after a while they noticed their device did not update. They usually uninstall the App (losing all changes) and reinstall to change their password. While they should change back the password at the Server (if possible), then sync, then change the server password and device password at the same time. But this is all too difficult, a change password option would save us all the hassle :)

**Comment by Kandru** [comment]
Would need this feature, too.

**Comment by zhorvath83** [comment]
This feature would be awesome!

**Comment by ennswi** [comment]
Implementent in Development branch and in the next release.
