### ISSUE TITLE
Account settings for Google doesn't work 

### ISSUE THREAD

**Issue by SoerenEilenberger** [ennswi/AndroidCaldavSyncAdapater#8]
Hi everyone, 

I managed to follow the fork though I'm rather a normal user... ;-) 
I want to use acaldav for syncing my Google Work account. It worked with the caldav sync adapter in version 1.80. In version 1.81 it didn't work as well as now in acaldav. 

Could you please look into the matter? It would be really appreciated! 

If I can be of any help, please tell me how! 
Best regards, Sören

**Comment by matthesrieke** [comment]
Hi Soeren. I have created a workaround (see #10). This works well for my google calendars, feel free to give it a try (once the PR is accepted, or via my fork from now on: https://github.com/matthesrieke/AndroidCaldavSyncAdapater).

**Comment by ennswi** [comment]
I implement the source from @matthesrieke and create a new release.
as soon as fdroid publish the release on the app store, you can test it.

**Comment by SoerenEilenberger** [comment]
Works fine, many thanks to Matthes and you!
