### ISSUE TITLE
Invalid Server answer, Check URL

### ISSUE THREAD

**Issue by jonnius** [ennswi/AndroidCaldavSyncAdapater#9]
I try to sync my owncloud calendar, but only get "Invalid Server answer, Check URL". The sync of the calender works well with Thunderbird (Lightning). What can I do?

**Comment by ennswi** [comment]
Hi,

Try copy the URL from your browser.
And use the caldav URL, not the URL for apple devices.

**Comment by jonnius** [comment]
I did those two but still get the same result.

**Comment by ennswi** [comment]
Did you have blanks in your URL?

**Comment by jonnius** [comment]
No, I don't. Is there a way to see the server answer?
In the past it already worked. Maybe it stopped working since my update to owncloud 7. But I have it strange, that it is working well with Thunderbird while not working with Android...

May you send me an email (jonatan_zeidler@gmx.de), so I could give you the URL and a account at my owncloud so that you can see it yourself?

**Comment by ennswi** [comment]
The server messages are in the log files from your webserver.

**Comment by jonnius** [comment]
Here is what I found in acces.log of my webserver nginx:

[IP-ADDRESS] - jonny [26/Feb/2015:12:33:38 +0000] "PROPFIND /remote.php/caldav/calendars/jonny/pers%C3%B6nlich/ HTTP/1.1" 207 413 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.4.0 Lightning/3.3.2"

[IP-ADDRESS] - - [26/Feb/2015:12:30:22 +0000] "PROPFIND /remote.php/caldav/calendars/jonny/pers%C3%B6nlich HTTP/1.1" 400 6985 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

The first one is by Thunderbird which is working well. The second one by CaldavSyncAdapter which does not work. What I can see so far is that there is a "jonny" (username) in front of the time stampt in the log of Thunderbird's call that is missing in CaldavSyncAdapter's call. May this be the reason?

**Comment by ennswi** [comment]
Hi,

 try to replace the %C3%B6 with 'ö'.

This is also a bug in this app.

If you want to bypass, than create a new calendar without letter like ö,ä,ü, ß.,,

**Comment by jonnius** [comment]
This is not the reason. I have another calender without any of these letter and facing the same problem...

**Comment by ennswi** [comment]
Can you post the name of the calendars, which doesn't work.
Then I can test these on my owncloud server.

**Comment by jonnius** [comment]
none of my calenders is working with CaldavSyncAdapter. Names of Calenders I tried: persönlich, familie, test.

**Comment by ennswi** [comment]
Hi,
if you use https and redirect all http requests to https.

then type https://<URL>

**Comment by jonnius** [comment]
I do use https and i type it.

**Comment by ennswi** [comment]
are you sure, that you configure you server corectly?

the log tells me that i get an http status code 400, from your server.

"failed org.apache.http.client.ClientProtocolException: StatusCode: 400"

**Comment by jonnius** [comment]
I am not experienced with configuring servers. But for Thunderbird is syncing, I guess the server should be configured correctly...

**Comment by de4niih** [comment]
I just wanted to share my experience with you guys. I just installed the App and configured my 
Kalender without any noticeable trouble.
@jonnius have you copy and pasted this URL ?
![scr_cloud dimsen de_2015-03-01_18-36-44](https://cloud.githubusercontent.com/assets/11258944/6431988/33c5a99c-c042-11e4-989e-7567c4a0a5fb.png)
As this just worked fine for me.

Im also running a own Owncloud8 Server on a Ubuntu Machine with latest Apache 2.4

On my device I'm running latest Android 5.0.2

**Comment by jonnius** [comment]
Yes, I copy and pasted this URL.  I am running Owncloud 7 with nginx (and PHP). I updated this App to Version 0.0.4. Still same result.

**Comment by de4niih** [comment]
@jonnius 
Thats strange. Could you may check your NGNIX error.log ?
As above mentioned youre getting a 400 error code when your Android is trying to connect to your OC Calender.

For comaprison, this is the output of my Apache access.log and for both I got the status code 207.
/_This line for the CalDav App_/
ip.ip.ip.ip - - [03/Mar/2015:13:10:56 +0100] "PROPFIND /remote.php/caldav/calendars/MyOCUserName/defaultcalendar HTTP/1.1" 207 108923 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

/_This line for Thunderbird Lightning_/
ip.ip.ip.ip - - [03/Mar/2015:13:13:57 +0100] "PROPFIND /remote.php/caldav/calendars/MyOCUserName/defaultcalendar/ HTTP/1.1" 207 5390 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Thunderbird/31.5.0 Lightning/3.3.2

**Comment by de4niih** [comment]
@jonnius @ennswi 
So I just setup a calender with ÄÜÖ's and added it to my Android Phone. For this Calender, I got these Apache access.log messages:

ip.ip.ip.ip - - [03/Mar/2015:13:30:44 +0100] "PROPFIND /remote.php/caldav/calendars/MyOCUserName/testcalwith%C3%84%C3%96%C3%9C HTTP/1.1" 401 1417 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

ip.ip.ip.ip - - [03/Mar/2015:13:30:44 +0100] "PROPFIND /remote.php/caldav/calendars/MyOCUserName/testcalwith%C3%84%C3%96%C3%9C HTTP/1.1" 207 2131 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

ip.ip.ip.ip - - [03/Mar/2015:13:30:44 +0100] "PROPFIND /remote.php/caldav/calendars/MyOCUserName/testcalwith%c3%84%c3%96%c3%9c/ HTTP/1.1" 207 1720 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

ip.ip.ip.ip - - [03/Mar/2015:13:30:44 +0100] "REPORT /remote.php/caldav/calendars/MyOCUserName/testcalwith%c3%84%c3%96%c3%9c/ HTTP/1.1" 207 3823 "-" "CalDAV Sync Adapter (Android) https://github.com/gggard/AndroidCaldavSyncAdapater Version:0.0.1"

**Comment by jonnius** [comment]
@de4niih As I mentioned above I get the same error using a calender without any "Umlaut" like äöü. The nginx error log doesn't show any error about this issue.
@ennswi As I mentioned above syncing works fine with Thunderbird. The test account from your server leads to the same: Thunderbird does the Job, the AndroidCaldavSync does not.

Any other idea?

**Comment by jonnius** [comment]
I tried syncing with https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=com.morphoss.acal on my phone and that app works well but does not put the dates into the android calendar. So the problem must be within this app. Should I open an issue on https://github.com/gggard/AndroidCaldavSyncAdapater for this App seems very similar and I get the same error there? Is this one a fork?

**Comment by ennswi** [comment]
@jonnius 
i make an new Release, can you test this bug?

**Comment by jonnius** [comment]
With the new version I get a "SSL error" because of the "Untrusted Certificate", even though I didn't set the "Check SSL Certificate" Checkbox.

**Comment by tmotard** [comment]
As Jonnius said, the last version sned a "SSL error". With or Whitouth setting the checkbox tu check SSL certificate.
Irollback and installed the previous version.
No problem with v0.5
thanks for your work

**Comment by Enrico204** [comment]
For untrusted certificates, see #29

**Comment by mariohofmann** [comment]
I read some bit of the comments. As you can see in comment of de4niih on 3 Mar 2015 the adapter appends an additional slash. This may be the main difference to mozialla thunderbird request could cause failed connection to ownCloud calendar.
